project:
  type: website
  resources:
    - CNAME
  output-dir: docs


website:
  title: "Saeed Salehi"
  description: "Associate Professor of Fluid Mechanics, Linköping University"
  site-url: "https://saeedsalehi.com"
  google-analytics: "G-Y03H51EZR6"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
