#!/usr/bin/env python3
"""Generate the news lists from news.yml.

Runs before every `quarto render` (see `pre-render` in _quarto.yml) and writes:

  _generated/news-recent.md  the latest HOME_COUNT items (summaries), for the home page
  _generated/news-all.md     every item (details), grouped by year, for news.qmd

To add news, put a new entry at the top of news.yml and re-render.
Requires PyYAML (python3-yaml).
"""

import calendar
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "news.yml"
OUT = ROOT / "_generated"
HOME_COUNT = 5
HEADER = "<!-- Generated by scripts/build_news.py from news.yml. Do not edit. -->\n\n"


def month_label(date, long=False):
    year, month = str(date).split("-")[:2]
    names = calendar.month_name if long else calendar.month_abbr
    return f"{names[int(month)]} {year}"


def load():
    items = yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or []
    ids = set()
    for item in items:
        for key in ("id", "date", "title", "summary"):
            if not item.get(key):
                raise SystemExit(f"news.yml: item {item.get('id', '?')!r} is missing '{key}'")
        if item["id"] in ids:
            raise SystemExit(f"news.yml: duplicate id {item['id']!r}")
        ids.add(item["id"])
        item["date"] = str(item["date"])
    # Newest first; items with the same month keep their order in the file.
    return sorted(items, key=lambda i: i["date"], reverse=True)


def recent(items):
    out = ["::: {.news-list}"]
    for item in items[:HOME_COUNT]:
        out += [
            "::: {.news-item}",
            f"[{month_label(item['date'])}]{{.news-date}}",
            "",
            item["summary"].strip(),
            ":::",
        ]
    out.append(":::")
    return "\n".join(out) + "\n"


def full(items):
    out, year = [], None
    for item in items:
        item_year = item["date"][:4]
        if item_year != year:
            year = item_year
            out += [f"## {year} {{#year-{year}}}", ""]
        out += [
            f"::: {{.news-entry}}",
            f"### {item['title']} {{#{item['id']}}}",
            "",
            f"[{month_label(item['date'], long=True)}]{{.news-date}}",
            "",
            (item.get("details") or item["summary"]).strip(),
            ":::",
            "",
        ]
    return "\n".join(out)


def main():
    items = load()
    OUT.mkdir(exist_ok=True)
    (OUT / "news-recent.md").write_text(HEADER + recent(items), encoding="utf-8")
    (OUT / "news-all.md").write_text(HEADER + full(items), encoding="utf-8")
    print(f"build_news: {len(items)} items, {min(HOME_COUNT, len(items))} on the home page")


if __name__ == "__main__":
    main()
